name: Build Workflow for text_console.exe/zip

on:
   push:
     tags:
       - "v*.*.*"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # Fetch all history for accurate commits and tags

      - name: Update VERSION in python file ui.py; commit and push updates
        run: |
          $filePath = "text_console/__version__.py"
          $VERSION = "${{ github.ref_name }}"
          if ($VERSION.StartsWith('v')) {
              $VERSION = $VERSION.Substring(1)
          }
          (Get-Content $filePath) -replace '^__version__ = ".*"$', "__version__ = `"$VERSION`"" | Set-Content $filePath
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://${GITHUB_USER}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add $filePath
          git commit -m "Update VERSION to ${{ github.ref_name }}"
          git push origin main

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Install Python Requirements
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Create wrapper
        run: |
          echo "import sys
          from text_console.__main__ import main
          sys.exit(main())" > text_console.py
        shell: pwsh

      - name: Run PyInstaller to produce the exe file
        run: |
          python -m PyInstaller --onefile text_console.py --name text_console --collect-all text_console

      - name: Zip the text_console.exe asset to text_console.zip
        run: |
          Compress-Archive dist/text_console.exe dist/text_console.zip
        shell: pwsh

      - name: Generate Changelog
        run: >
          echo "The *text_console.exe* executable file in the
          *text_console.zip* archive within the assets below is
          auto-generated by a [GitHub Action](.github/workflows/build.yml).
          <br /><br />
          Check the
          [History of modifications](https://github.com/Ircama/text_console/commits/main/).
          "
          > ${{ github.workspace }}-CHANGELOG.txt

      - name: Create Release, uploading the text_console.zip asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: ${{ github.workspace }}-CHANGELOG.txt
          files: dist/text_console.zip
          append_body: true
          generate_release_notes: false

      - name: Remove old releases
        uses: Nats-ji/delete-old-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-count: 1
          keep-old-minor-releases: false
          keep-old-minor-releases-count: 1
          remove-tags: true
