name: Publish Package to PyPI and TestPyPI

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Build Workflow for text_console.exe/zip"]
    types: [completed]

jobs:
  build-and-publish:
    name: Build and Publish Python Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install build dependencies
        run: pip install setuptools wheel twine build

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload --repository pypi dist/* --verbose

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          twine upload --repository testpypi dist/*.tar.gz --verbose
